### ISSUE TITLE
Button does not appear on Netflix

### ISSUE THREAD

**Issue by elifoster** [JoeKuhns/PiedPiPer.safariextension#2] opened 2016-10-13 04:48 UTC
Using 1.90 of the extension, the PiP button does not appear when using Netflix. Looking at others' screenshots of this, it appears as though it should be where the "HD" button is. Perhaps this is the source of the issue?

**Comment by JoeKuhns** [comment] 2016-10-13 11:02
I can't reproduce.  What video are you playing?  The button should be to the right of the title.  

After a quick google, it still looks like you are using Netflix with the silverlight player.  Press CTRL+OPT+SHIFT+S.   Do you get a menu of bitrates?  If not, check your playback setting under my account on Netflix.

**Comment by JoeKuhns** [comment] 2016-10-13 19:33
Gonna close this as I am sure you are using the silverlight player in Netflix.  Which means you are not using Sierra or you machines specs are too old for Netflix to allow html5 video.

**Closed as completed by JoeKuhns** 2016-10-13 19:33 UTC
Labels: wontfix

**Comment by elifoster** [comment] 2016-10-13 19:45
Ah, indeed. "Early 2011 model or newer Mac" Computer's about half a year too old to use the HTML5 player I suppose.

Edit: Since it's not actually a bug, "invalid" would probably be a more logical label :wink:
